### ISSUE TITLE
Make Chocomilk able to handle semantic versioning

### ISSUE THREAD

**Issue by FreeMinded** [open-circle-ltd/chocomilk#2]
Currently Chocomilk fails to recognize 1.10.0 as newer than 1.9.0

Ansible provides an Version Test (https://docs.ansible.com/ansible/devel/collections/ansible/builtin/version_test.html) which seems to be able to handle different versioning schemes including semantic. 

If I'm not mistaken the following section would need to be changed.
https://github.com/open-circle-ltd/chocomilk/blob/90ceb3944ca998cac920df4b8c98ff00c345646e/package/version.yml#L19

**Comment by FreeMinded** [comment]
Hint
`
- name: Compare versions
  set_fact:
    newer_version: "{{ current_version is version_compare(new_version, 'gt') }}"
`

**Comment by sbaerlocher** [comment]
The error has been fixed using the string: `current_version is version(available_version, '<')`
